### ISSUE TITLE
Doesn't install 2.15

### ISSUE THREAD

**Issue by gisborne** [dart-lang/homebrew-dart#100]
Android Studio told me that 2.15 is available. But I just get this:

`% brew upgrade dart
Warning: dart-lang/dart/dart 2.14.2 already installed`

**Comment by athomas** [comment]
This seems like a bug in Android Studio given that 2.15 wasn't available back then: [2.15.0 - 2021-12-08](https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#2150---2021-12-08)
