### ISSUE TITLE
Dart 2.19 is missing

### ISSUE THREAD

**Issue by sasuw** [dart-lang/homebrew-dart#152]
The version 2.19 is missing. The latest 2.x version found with Homebrew is 2.18. 

`brew install "dart-lang/dart/dart@2.18"`

works, 

`brew install "dart-lang/dart/dart@2.19"`

does not. I have run brew update beforehand. `brew search dart` shows only versions up to 2.18.

**Comment by whesse** [comment]
That is correct, we have not yet made that formula.  We should do this whenever we increase the version number, so we should have done this at the time that Dart 3.0 was released.  I will do this soon. Until then, you can download the SDK directly as a zip file from https://dart.dev/get-dart/archive

**Comment by whesse** [comment]
This is complete, and dart@2.19 exists.
