### ISSUE TITLE
Unable to upgrade to dart 1.8?

### ISSUE THREAD

**Issue by nicolasgarnier** [dart-lang/homebrew-dart#17]
Just tried to upgrade to Dart 1.8 through brew upgrade and got this:

```
nivco> brew upgrade dart
Error: dart-1.7.2 already installed
```

**Comment by davidair** [comment]
Just had the same problem upgrading to Dart 2.10.1 from 2.7.1 - I needed to follow the workaround by @nicolasgarnier and to do an untap followed by tap. This is not mentioned on https://dart.dev/get-dart :(
