### ISSUE TITLE
pub build (transformers) unable to infer dart-sdk location.

### ISSUE THREAD

**Issue by bgourlie** [dart-lang/homebrew-dart#18]
I'm attempting to run the angular transformer on a project and I get the following error: 
`Loading angular transformers...`
`Error on line 15, column 3 of pubspec.yaml: Error loading transformer: Invalid arguments(s): sdkDirectory must be provided.`

After a bit of researching, I believe this is because pub cannot infer the location of the dart-sdk due to where the brew formula is putting files.

**Comment by andrew-luhring** [comment]
What's the solution to this? 
What do I do?
```"pubspec.yaml:Error loading transformer: Invalid arguments(s): sdkDirectory must be provided." ```
in pubspec.yaml should I do something like add:

```
sdkDirectory: /Applications/dart/dart-sdk/
```
?

(I tried that and it doesn't work... I don't know the syntax of whatever it would be)
