### ISSUE TITLE
Please define best practices

### ISSUE THREAD

**Issue by rightisleft** [dart-lang/homebrew-dart#29]
Can you please outline best practices for using Dart Editor with this formula in the README. 

In the editor.properties file I'm providing the variable
dart.sdk=/usr/local/Cellar/dart/1.8.5/ 

This works well enough. However, this file seems to get over written by the Dart Editor upgrade process.

**Comment by sethladd** [comment]
Hi, thanks for the report.

Can you please file an issue for the Editor at http://dartbug.com/new ? 

Meanwhile, you should use this directory: `/Users/sethladd/homebrew/opt/dart/libexec` for your SDK home.

I'll close this here, as the issue seems to be with Editor overwriting your file.

**Comment by rightisleft** [comment]
Thanks - opened here https://code.google.com/p/dart/issues/detail?id=22919

**Comment by rightisleft** [comment]
Is there a work around for the following:

Could not find dartium executable in /usr/local/Cellar/dart/chromium 

when using:

dart.sdk=/usr/local/Cellar/dart/1.8.5/

**Comment by sethladd** [comment]
I think dartium is installed into a different directory. I assume you also installed Dartium (brew install dartium)?

Do an `ls` in `/usr/local/Cellar` to see what's in there.

Sorry I don't have the specifics right now.

**Comment by rightisleft** [comment]
Sorry my above post was not specific enough:

i've executed 'brew install dart dartium' which executed both formulas and installed them to their respective directories. 

/usr/local/Cellar/dart/1.8.5/
/usr/local/Cellar/dartium/1.8.5/

Apparently Dart Editor tends to look for the chromium executable in the parent folder of the dart-sdk containers (this is how the bundle is setup). 

So by defining dart.sdk=/usr/local/Cellar/dart/1.8.5/ - on chromium launch - the dart editor looks in /usr/local/Cellar/dart/ instead of the formula location of /usr/local/Cellar/dartium/1.8.5/

This is why i was asking for best practices in relationship to using the Dart Editor with this forumla. I can create a bunch of symlinks, but that seems to reduce the usefulness of using brew in the first place.

**Comment by sethladd** [comment]
Great question. Can you please email editor@dartlang.org, as that is the mailing list that is watched by the Dart Editor team. Thanks!
