### ISSUE TITLE
"You are using an unsupported command-line flag: --no-sandbox"

### ISSUE THREAD

**Issue by davenotik** [dart-lang/homebrew-dart#30]
After `brew upgrade dart dartium`:

"You are using an unsupported command-line flag: --no-sandbox. Stability and security will suffer."

http://d.pr/i/WehX

**Comment by sethladd** [comment]
I believe this is expected. Also, this isn't a homebrew issue. I'm going to close this out here. However, we probably need to update documentation on Dartium. I filed https://github.com/dart-lang/www.dartlang.org/issues/1308 to track.

Thanks for the head's up!
