### ISSUE TITLE
[dartium] Version missing in filename “dartium--content_shell-macos.zip”

### ISSUE THREAD

**Issue by fuzzykiller** [dart-lang/homebrew-dart#36]
...resulting in the following error:

    ==> Upgrading dart-lang/dart/dartium
    ==> Downloading https://storage.googleapis.com/dart-archive/channels/stable/release/1.11.3/dartium/dartium-ma
    ######################################################################## 100,0%
    ==> Downloading https://storage.googleapis.com/dart-archive/channels/stable/release/1.11.3/dartium/content_sh
    Already downloaded: /Library/Caches/Homebrew/dartium--content_shell-macos.zip
    Error: SHA256 mismatch
    Expected: 04199ec06dd3dc94ef219f1817a34cf6f4c9ec7650bd1f597fb5155ebd9abe94
    Actual: cbde87a5becb2ca4c8256e624a2eab6943df26f58125cb2b65cc38496c15f3a9
    Archive: /Library/Caches/Homebrew/dartium--content_shell-macos.zip
    To retry an incomplete download, remove the file above.

**Comment by whesse** [comment]
There is an error in the deprecated dartium formula.  Use the dart formula with --with-dartium and --with-content-shell instead.  We will remove the dartium formula, and it will only print an error message pointing to the dart formula.
