### ISSUE TITLE
Out of Date with Webstorm

### ISSUE THREAD

**Issue by rightisleft** [dart-lang/homebrew-dart#37]
This is referenced in the official docs.

This is out of date.

The current 1.11.3 version does not meet the min reqs for latest WebStorm dart plugin of 1.12

**Comment by sethladd** [comment]
Hi. What version of the WebStorm plugin are you using?

Also, Dart SDK 1.12 was just released. Can you give it a try?

**Comment by rightisleft** [comment]
IntelliJ IDEAUltimate EAP 15 - but that should still be using the same dart plugin.

Dart Plugin 142.4148

I'll give the new version a test

**Comment by rightisleft** [comment]
Looks like Jetbrains jumped the gun. Most recent release works now.

Thanks!

**Comment by sethladd** [comment]
Thanks for checking!
