### ISSUE TITLE
Can't upgrade dart with brew

### ISSUE THREAD

**Issue by kelegorm** [dart-lang/homebrew-dart#39]
$ brew upgrade
==> Upgrading 3 outdated packages, with result:
dart-lang/dart/dart 1.13.0-dev.5.0, git 2.6.0, libusb 1.0.20
==> Upgrading dart-lang/dart/dart
Error: The following formula:
  dart
cannot be installed as a a binary package and must be built from source.
To continue, you must install Xcode from the App Store,
or the CLT by running:
  xcode-select --install

**Comment by whesse** [comment]
I don't see anything that changed in the 1.13.0-dev.5.0 release from earlier releases.  Did you change anything on your system, like upgrading the OS?  It may be that you need to install xcode, even though there is no compilation needed for the Dart tools.  I don't know if anyone has installed it without having xcode installed.  Though if that is the issue, we should fix it.

Can you upgrade to an earlier version, by specifying it?   Could you try uninstalling it and instaling it again, and clearing your Homebrew cache?

**Comment by kelegorm** [comment]
Hm. Yes, I have updated OS X. But I suppose I had not XCode before.

**Comment by kelegorm** [comment]
I have removed dart package, called `$brew cleanup`, and '$brew install dart --devel'. It shows same message about XCode. So, may be there is real problem?

**Comment by sethladd** [comment]
I was in a hackathon yesterday, and most of us used homebrew and were able to download the latest dev channel.

Maybe, you could paste in the set of commands you're using and all their output, and we can see if we spot anything odd.

Sorry for the trouble!

**Comment by sethladd** [comment]
Going to close, but if this is still an issue, please let us know!

**Comment by kelegorm** [comment]
I can'w wait, I must work :) I have installed xcode weeks ago and now I don't know if there is bug.

**Comment by sethladd** [comment]
Do this:

* brew update
* brew uninstall dart
* brew install dart

What happens?

**Comment by kelegorm** [comment]
It's updating and doesn't illuminate problem I had before as i have already xcode installed.

**Comment by sethladd** [comment]
OK, thanks for checking. Glad it's updating.
