### ISSUE TITLE
Linuxbrew Support

### ISSUE THREAD

**Issue by kendfinger** [dart-lang/homebrew-dart#42]
I'm filing this issue to track work I am doing to support Linuxbrew. This will make the Dart Tap work with Linux and Mac, without any effort required.

**Comment by whesse** [comment]
Great!  Will this tap be a different repo than the existing homebrew one?

**Comment by kaendfinger** [comment]
I don't think so, I think I will do it in this tap. It's pretty simple, you just add an argument to the 'url' for resources, and wrap the Mac specific stuff in OS.linux? checks. I will also write a tool to auto-generate this, if that is something you are interested in.

**Comment by whesse** [comment]
Yes, the entire dart formula here is auto-generated by https://github.com/dart-lang/sdk/blob/master/tools/apps/update_homebrew/bin/update_homebrew.dart

So to make changes, you should change that script in the sdk repo.

**Comment by kaendfinger** [comment]
Awesome!

**Comment by sestegra** [comment]
Merge done, this issue could be closed
