### ISSUE TITLE
Versioning support

### ISSUE THREAD

**Issue by Anrock** [dart-lang/homebrew-dart#46]
It would be cool, if this tap provided formulas for all major/minor versions: 1.23, 1.22.1 and so on.

**Comment by Keksinautin** [comment]
Hi, we here at Wrike have the same pain with it, because we as a big company have to use particular versions of the Dart-SDK and switch between them from time to time.

**Comment by Allan-Nava** [comment]
Is possible to install 2.1.0 dart not the development version?

**Comment by jasonclouse-wk** [comment]
This is desperately needed.

**Comment by craiglabenz** [comment]
Bump on this issue -- it would be very nice to install specific versions with `brew install dart@VERSION` :smile:
