### ISSUE TITLE
Dart 1.24.3 release

### ISSUE THREAD

**Issue by sestegra** [dart-lang/homebrew-dart#47]
Dart 1.24.3 is available on https://www.dartlang.org/install/archive, but Dartium and Content-shell not.

Will you release 1.24.3 brew version ?

**Comment by Stargator** [comment]
Looping in @whesse @sethladd @kevmoo

**Comment by MikeMitterer** [comment]
https://github.com/dart-lang/sdk/issues/31674#issuecomment-352525764

**Comment by whesse** [comment]
We don't have a Dartium or content-shell built for 1.24.3 yet.  They would be identical to the 1.24.2 versions: the only change in 1.24.3 are some secure socket operations on server-side Dart (the dart executable).  We are considering how to fix the release channels now.

**Comment by MikeMitterer** [comment]
content-shell for Mac fail (hang) anyway... - I think since 1.24.0

**Comment by Stargator** [comment]
Would it be possible to keep the 1.24.2 support as a way to support versioning as requested: #46

And then just add 1.24.3 on top?

**Comment by kevmoo** [comment]
> Would it be possible to keep the 1.24.2 support as a way to support versioning as requested

I think homebrew only supports "normal" and dev flavors.

...unless there is a new feature I'm not aware of...

**Comment by MikeMitterer** [comment]
It's not that big deal but just a bit confusion. IntelliJ tells me every day that a new version is available then I go to check this on homebrew which tells me that there is no new version for Mac. 

![capturfiles-20171220_105902](https://user-images.githubusercontent.com/116654/34201485-eb808c00-e574-11e7-87c7-46488c4718ef.png)

**Comment by whesse** [comment]
Dart 1.24.3 should now be available on Homebrew.  The dartium and content_shell versions that it will download (if you provide those options) will be 1.24.2, but those are unchanged in 1.24.3.  We are in the process of deciding whether to build 1.24.3 dartium and release it
