### ISSUE TITLE
Automatically add pub-cache to path

### ISSUE THREAD

**Issue by passsy** [dart-lang/homebrew-dart#50]
To run programs activated with `pub global activate` one has to [**manually** add `/Users/<user>/.pub-cache/bin` to `path`](https://www.dartlang.org/tools/pub/cmd/pub-global#running-a-script-from-your-path). This could be automated by this recipe.

**Comment by sortie** [comment]
Hmm. Interesting idea. Though we don't make the Dart SDK installation do this on any other platform, so I won't make that change, so the Dart experience is consistent across installation methods.
