### ISSUE TITLE
How can I install a specific version of dart?

### ISSUE THREAD

**Issue by chstrongsg** [dart-lang/homebrew-dart#54]
2.0.0-dev.64.1 is broken, or at least it broke AngularDarts webdev serve. How can I downgrade to 2.0.0-dev.60.1?

**Comment by athomas** [comment]
Without more context, I would say that's intentional, see this announcement:
https://groups.google.com/a/dartlang.org/d/msg/announce/R4kV3us0Sm8/FuuBJ3bxAQAJ
https://webdev.dartlang.org/dart-2 

To get an old version, this should help: https://danepowell.com/blog/homebrew-formula-versions

**Comment by kevmoo** [comment]
We need to release a new version of `webdev` – I'm working on that in the next couple of hours.
