### ISSUE TITLE
MacOS.prefer_64_bit is deprecated.

### ISSUE THREAD

**Issue by voldemortensen** [dart-lang/homebrew-dart#58]
While upgrading dart I received this error:
`Error: dart-lang/dart/dart: undefined method `prefer_64_bit?' for OS::Mac:Module`

Upon further investigation I found that the `prefer_64_bit` method has been deprecated. See https://github.com/Homebrew/brew/commit/170c5493a4e3628ed77137215a9ed6328e1a17c8#diff-1c1e64ec9fa3342388d0ddb7a9607eca

The new way to check is the `is_64_bit` method.

**Comment by kevmoo** [comment]
CC @whesse @athomas – should be an easy fix

**Comment by rezam90** [comment]
Hi, it still gives the error. Isn't it fixed yet?

**Comment by AlexGHancock** [comment]
Same problem here... Perhaps I should downgrade homebrew to get it working?

**Comment by kevmoo** [comment]
This is not completely fix yet – Need to update https://github.com/dart-lang/sdk/tree/master/tools/apps/update_homebrew too!

**Comment by kevmoo** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/8719fb3a7b8e8bf0b0d5df8ef389cd039b1fd6f0

**Comment by voldemortensen** [comment]
Thanks for the fix!
