### ISSUE TITLE
update to fix the dev version hicup

### ISSUE THREAD

**Issue by rayk** [dart-lang/homebrew-dart#62]
@athomas I am not sure if you saw this, https://github.com/dart-lang/sdk/issues/35861, we can update  dart.rb to pick the new version?

**Comment by athomas** [comment]
2.1.1-dev.3.2 is the newest version. 2.2.0-dev.x.x are the hiccups.

**Comment by rayk** [comment]
Thanks @athomas , looking at the release page, I thought 2.1.2-dev.0.0 was the lastest. https://github.com/dart-lang/sdk/releases/tag/2.1.2-dev.0.0

**Comment by athomas** [comment]
2.1.2 is tagged, and built and currently undergoing additional release testing. It has not been published, yet.

**Comment by rayk** [comment]
Thanks
