### ISSUE TITLE
Update Existing Global Packages on Update of Dart

### ISSUE THREAD

**Issue by mohammed90** [dart-lang/homebrew-dart#64]
Dart programs installed with `pub global activate` will not work after updates of Dart, complaining about kernel incompatibility. The fix is to do `pub global activate {{package}}` after every Dart update. It is less of a hassle for the end-user/developer to have them auto-updated once Dart is updated.

For posterity, I've been using this one-liner after Dart updates to update all installed global packages:
```shell
dart pub global list | awk '{system("dart pub global activate " $1)}'
```

**Comment by sortie** [comment]
Hmm. I do see that's a real pain. No other installation method of the Dart SDK does this for you though, so I'm reluctant to make the homebrew package special in this way. This may rather be an issue for the pub team at https://github.com/dart-lang/pub to think about.
