### ISSUE TITLE
brew install dart  —— Error: Xcode alone is not sufficient on Mojave

### ISSUE THREAD

**Issue by yibit** [dart-lang/homebrew-dart#68]
MacBook-Pro:~ ruby$ brew tap dart-lang/dart
MacBook-Pro:~ ruby $ brew install dart
==> Installing dart from dart-lang/dart
Error: Xcode alone is not sufficient on Mojave.
Install the Command Line Tools:
  xcode-select --install

There are two versions of Xcode on my MacBook Pro 2019:

Xcode Version 10.2.1 (10E1001)
Xcode-beta

**Comment by yibit** [comment]
I have fixed this issue by install Command_Line_Tools_macOS_10.14_for_Xcode_10.2.1 from
https://developer.apple.com/download/more/. 
Thank you very much!

**Comment by frederic33** [comment]
I have fixed this issue by install Command_Line_Tools_macOS_10.14_for_Xcode_10.3.1 from Apple dev link !!!
Nice Yibit ;)

**Comment by jesphinpt** [comment]
For the above, did you use the Xcode and command-line tool as well?

I have Xcode and set the path in the location of the Xcode. Still, it shows the above error in the big sur. So shall I need to install the command-line tool as well?
