### ISSUE TITLE
Homebrew Deprecation DEVEL

### ISSUE THREAD

**Issue by sarvex** [dart-lang/homebrew-dart#76]
Warning: Calling 'devel' blocks in formulae is deprecated! Use 'head' blocks or @-versioned formulae instead.
Please report this issue to the dart-lang/dart tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/dart-lang/homebrew-dart/dart.rb:29

**Comment by athomas** [comment]
Thanks for the PR, we ended up merging #78 to address this.
