### ISSUE TITLE
Bad cpu type error with m1 mac

### ISSUE THREAD

**Issue by lewisthoma5** [dart-lang/homebrew-dart#95]
```
thomas@Thomass-Air ~ % dart
zsh: bad CPU type in executable: dart
```

It seems the current repo does not support m1 natively.

**Comment by athomas** [comment]
Yes, until yesterday we only supplied the x64 versions on M1 macs (those run fine if rosetta is enabled). We are now having native M1 versions on the dev and beta channels on homebrew. I don't know yet when it will be enabled on stable.
